[project]
name = "training"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-tunix",
    "ipdb>=0.13.13",
    "wandb>=0.23.0",
]

[tool.uv.sources]
google-tunix = { git = "https://github.com/google/tunix" }
